  image: node:10:16:3

    cache:
      paths:
        - node_modules/

    install_dependencies:
      stage: build
      script:
        - npm install
      artifacts:
        paths:
          - node_modules/

    testing:
      stage: test
      script: 
      - npm test